/** The four player weapons available in the browser game. */

import type { WeaponSpec } from "./types";

export const WEAPONS: Record<string, WeaponSpec> = {
  ash_blade: {
    id: "ash_blade",
    name: "ASH BLADE",
    style: "blade",
    lightReach: 82,
    lightHeight: 62,
    lightDamage: 31,
    lightTime: 0.32,
    lightActive: [0.1, 0.22],
    lightStamina: 14,
    heavyReach: 112,
    heavyHeight: 82,
    heavyDamage: 54,
    heavyTime: 0.58,
    heavyActive: [0.16, 0.38],
    heavyStamina: 34,
  },
  twin_fangs: {
    id: "twin_fangs",
    name: "TWIN FANGS",
    style: "daggers",
    lightReach: 64,
    lightHeight: 56,
    lightDamage: 22,
    lightTime: 0.24,
    lightActive: [0.07, 0.17],
    lightStamina: 10,
    heavyReach: 88,
    heavyHeight: 70,
    heavyDamage: 40,
    heavyTime: 0.46,
    heavyActive: [0.12, 0.3],
    heavyStamina: 26,
  },
  ember_maul: {
    id: "ember_maul",
    name: "EMBER MAUL",
    style: "hammer",
    lightReach: 92,
    lightHeight: 70,
    lightDamage: 42,
    lightTime: 0.44,
    lightActive: [0.14, 0.3],
    lightStamina: 20,
    heavyReach: 126,
    heavyHeight: 92,
    heavyDamage: 74,
    heavyTime: 0.74,
    heavyActive: [0.22, 0.48],
    heavyStamina: 44,
  },
  warden_spear: {
    id: "warden_spear",
    name: "WARDEN SPEAR",
    style: "spear",
    lightReach: 118,
    lightHeight: 50,
    lightDamage: 27,
    lightTime: 0.36,
    lightActive: [0.11, 0.24],
    lightStamina: 15,
    heavyReach: 150,
    heavyHeight: 64,
    heavyDamage: 48,
    heavyTime: 0.62,
    heavyActive: [0.18, 0.4],
    heavyStamina: 36,
  },
};

export const DEFAULT_WEAPONS = ["ash_blade", "twin_fangs"];
export const WEAPON_UNLOCKS: Record<string, string> = {
  root_warden: "ember_maul",
  bell_keeper: "warden_spear",
};
